rename LandAlb.png LandALB.png
rename LandAnf.png LandANF.png
rename LandBft.png LandBFT.png
rename LandBoc.png LandBOC.png
rename LandCod.png LandCOD.png
rename LandCre.png LandCRE.png
rename LandCut.png LandCUT.png
rename LandHad.png LandHAD.png
rename LandHer.png LandHER.png
rename LandHke.png LandHKE.png
rename LandJax.png LandJAX.png
rename LandJod.png LandJOD.png
rename LandLem.png LandLEM.png
rename LandLez.png LandLEZ.png
rename LandLin.png LandLIN.png
rename LandMac.png LandMAC.png
rename LandNep.png LandNEP.png
rename LandPle.png LandPLE.png
rename LandPok.png LandPOK.png
rename LandPol.png LandPOL.png
rename LandRaj.png LandRAJ.png
rename LandSca.png LandSCA.png
rename LandSol.png LandSOL.png
rename LandSpr.png LandSPR.png
rename LandSqu.png LandSQU.png
rename LandWhb.png LandWHB.png
rename LandWhg.png LandWHG.png
rename LandWit.png LandWIT.png
