##  Downloading your stock from Standarad Graphs
##           Ver 0.1 Colm Lordan
##           Ver 0.2 Siobhan Moran adapting Hans Gerritsen code. 


# install from CRAN
#install.packages("icesSAG")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#2022  ##
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The original code in 'SAG_downloadv3_tryFunction.R' produced empty files. 
# Hans code in Z:\StockBooks\_Stockbook2022\MiSummaryOfAdvice\SAG plots.R' produced viable files
# This code was adapted and merged with the original code to produce the following script.
# Please note: In 2022 HG's token was used. Please see the instructions below to generate a new token for 2023


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#2021  ## using 'SAG_downloadv3_tryFunction.R'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Installed package 'icesVocab'
#click on 'icesVocab' in the list to the right to give
#library("icesVocab", lib.loc="~/R/win-library/4.0")
#click on 'png' in the list to the right to give
#library("png", lib.loc="~/R/win-library/4.0")
#click on 'icesSAG' in the list to the right to give
#library("icesSAG", lib.loc="~/R/win-library/4.0")
#OR See Step 1 below. 


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#2020 warning  !!   ##
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Warning in install.packages :
#  package icesSAG is not available (for R version 4.0.2)

#Package icesSAG was removed from the CRAN repository.
#Formerly available versions can be obtained from the archive.
#Archived on 2020-08-07 as it requires archived package 'icesVocab'.

#STEP 1
#downloaded the latest tar.gz from https://cran.r-project.org/src/contrib/Archive/icesSAG/
#open 'install'  - whan the pop-up box opens, select 'Package Archive File', from the first drop down box.
#Browse to the downloaded tar.gx file location and install. 

#Got an error message - ERROR: dependency 'png' is not available for package 'icesSAG'
#* removing 'C:/Users/smoran/Documents/R/win-library/4.0/icesSAG'

#STEP 2
#install 'png' package, then repeat STEP 1 and continue
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



library(icesVocab)
library(png)
library(icesSAG)

#update wd 
#setwd("Z:/InformaticsProject/Phase1/Stockbook Handover/2021_Git/www/ICES")
setwd("Z:/InformaticsProject/Phase1/Stockbook Handover/2022_Git/digital-stockbook/www/ICES")

IrishStocks=read.csv("stock_lookupV2.csv", header=TRUE)
dim(IrishStocks)
head(IrishStocks)
colnames(IrishStocks) <- c("ecoregion","Old","species type" ,"New","x")
stocks <- IrishStocks$New



#~~~~~~  2022  ~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~
#Sep 02nd - changed the file path to '....2022_Git\digital-stockbook\' 
#Manually add a 2022 folder in each ICES folder, for the downloaded png's to be saved into

#UPDATE PATHS

# Example of how to register a token (from HG code) 
# You can generate a token like this:
#  first log in on  https://standardgraphs.ices.dk/manage
#  then go to sg.ices.dk/manage/CreateToken.aspx
#  paste the token below after SG_PAT=

#this token was generated by RD on Oct 05th 2022 for 100 days
if(F){
  cat("# Standard Graphs personal access token",
      "SG_PAT=c19d7e92-3c29-476f-8186-0b813fb42f32",
      sep = "\n",
      file = "~/.Renviron_SG")
}
options(icesSAG.use_token = TRUE)

## STATUS folder ##
for(i in  stocks){
  cat(i,'\n')
  year <- 2022
  key <- findAssessmentKey(i, year, regex = TRUE, full = FALSE)
  
  if(length(key)>0) {
    
    a <- try(getStockStatusTable(key)) 
    png(file=paste("Z:/InformaticsProject/Phase1/Stockbook Handover/2022_Git/digital-stockbook/www/ICES/Status/2022/", i, ".png", sep=""), width=dim(a[[1]])[2],height=dim(a[[1]])[1])
    plot(a)
    dev.off()
  }
}

## SAG folder (Stock Development Over Time) ##
for(i in  stocks){
  cat(i,'\n')
  year <- 2022
  key <- findAssessmentKey(i, year, regex = TRUE, full = FALSE)
  
  if(length(key)>0) {
    b <- try(getSAGGraphs(key))
        if(class(b)=='try-error') next()
        try(png(file=paste("Z:/InformaticsProject/Phase1/Stockbook Handover/2022_Git/digital-stockbook/www/ICES/SAG/2022/", i, ".png", sep=""), width=dim(b[[1]])[2]*4,height=dim(b[[1]])[1]*4))
        plot(b)
        dev.off()
  }
} 
  
# SSB folder (Quality of Assessment) ##
# for(i in  stocks){
#   cat(i,'\n')
#   year <- 2022
#   key <- findAssessmentKey(i, year, regex = TRUE, full = FALSE)
# 
#   if(length(key)>0) {
#     c <-  try (getSSBHistoricalPerformance(key))
#         if(class(b)=='try-error') next()
#         png(file=paste("Z:/InformaticsProject/Phase1/Stockbook Handover/2022_Git/digital-stockbook/www/ICES/SSB/2022/", i, ".png", sep=""), width=dim(c[[1]])[2],height=dim(c[[1]])[1])
#         plot(c)
#         dev.off()
#   }
# }

#This ORIGINAL LOOP CODE FOR SSB worked on Sept 05th 2022! Last years code - though the majority are 1kb....
#This also worked on Oct 05th (the above loop from HG only downloaded 1 stock that day: ank.27.78ab). Again the majority are 1kb
#Quality of Assessment (SSB) 
for(i in  IrishStocks$New){
  print (i)
  graphs <- NA
  try (graphs <- getSSBHistoricalPerformance(findAssessmentKey(i, 2022)[1]))
  if (! is.na(graphs)) {
    png(file=paste("Z:/InformaticsProject/Phase1/Stockbook Handover/2022_Git/digital-stockbook/www/ICES/SSB/2022/", i, ".png", sep=""),
        width = 450, height = 350)
    plot(graphs)
    dev.off()
  }
}


# ## Fishmort folder ## HG CODE
# for(i in  stocks){
#   cat(i,'\n')
#   year <- 2022
#   key <- findAssessmentKey(i, year, regex = TRUE, full = FALSE)   
#     
#   ##if(length(key)>0) {
#     if (! is.na(key)) {
#       if(class(d)=='try-error') next()
#     d <-   try (getFishingMortalityHistoricalPerformance(key))
#         png(file=paste("Z:/InformaticsProject/Phase1/Stockbook Handover/2022_Git/digital-stockbook/www/ICES/Fishmort/2022/", i, ".png", sep=""), width=dim(d[[1]])[2],height=dim(d[[1]])[1])
#         plot(d)
#         dev.off()
#   }
# } 
#ERROR MESSAGE - (no graphs were saved)
# ank.27.78ab 
# GETing ... https://sg.ices.dk/Manage/StockAssessmentGraphsWithToken.asmx/getListStocks?year=2022&token=c19d7e92-3c29-476f-8186-0b813fb42f32
# Error in class(d) : object 'd' not found
# In addition: Warning message:
#   In if (!is.na(key)) { :
#       the condition has length > 1 and only the first element will be used
#     


 
#This ORIGINAL LOOP CODE FOR Fishmort worked on Oct 05th (the above loop from HG downloaded no stocks that day). The majority are 1kb
#Quality of Assessment (SSB) 
for(i in  IrishStocks$New){
  print (i)
  graphs <- NA
  try (graphs <- getFishingMortalityHistoricalPerformance(findAssessmentKey(i, 2022)[1]))
  if (! is.na(graphs)) {
    png(file=paste("Z:/InformaticsProject/Phase1/Stockbook Handover/2022_Git/digital-stockbook/www/ICES/Fishmort/2022/", i, ".png", sep=""),
        width = 450, height = 350)
    plot(graphs)
    dev.off()
  }
}
#At Nephrops it stopped and GAVE A WARNING MESSAGE, then after a few minutes, continued to pull the graphs:-)


# ## RecruitHist folder ## HG CODE FAILED
# for(i in  stocks){
#   cat(i,'\n')
#   year <- 2022
#   key <- findAssessmentKey(i, year, regex = TRUE, full = FALSE)   
#   
#   if(length(key)>0) {
#     e <-   try (getRecruitmentHistoricalPerformance(key))
#         png(file=paste("Z:/InformaticsProject/Phase1/Stockbook Handover/2022_Git/digital-stockbook/www/ICES/RecruitHist/2022/", i, ".png", sep=""), width=dim(e[[1]])[2],height=dim(e[[1]])[1])
#         plot(e)
#         dev.off()
#         
#       }
#     }


#This ORIGINAL LOOP CODE FOR RecruitHist worked on Oct 05th (the above loop from HG downloaded no stocks that day). They are ALL 1kb!! 
for(i in  IrishStocks$New){
  print (i)
  graphs <- NA
  try (graphs <- getRecruitmentHistoricalPerformance(findAssessmentKey(i, 2022)[1]))
  if (! is.na(graphs)) {
    png(file=paste("Z:/InformaticsProject/Phase1/Stockbook Handover/2022_Git/digital-stockbook/www/ICES/RecruitHist/2022/", i, ".png", sep=""),
        width = 450, height = 350)
    plot(graphs)
    dev.off()
  }
}
     
    